# Generated by Django 5.1.5 on 2025-09-11 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0028_remove_energyconsumption_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50, unique=True)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('oace', models.CharField(default='MES', max_length=10)),
                ('osde', models.CharField(default='MES', max_length=10)),
                ('codcli', models.CharField(blank=True, max_length=20)),
                ('control', models.CharField(blank=True, max_length=10)),
                ('ruta', models.CharField(blank=True, max_length=10)),
                ('folio', models.CharField(blank=True, max_length=10)),
                ('nombre_empresa', models.CharField(default='Universidad de Camaguey', max_length=100)),
                ('codigo_reeup', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('plan_total_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provincia', models.CharField(default='CAMAGUEY', max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('oace', models.CharField(default='MES', max_length=10)),
                ('osde', models.CharField(default='MES', max_length=10)),
                ('codcli', models.CharField(blank=True, max_length=20)),
                ('control', models.CharField(blank=True, max_length=10)),
                ('ruta', models.CharField(blank=True, max_length=10)),
                ('folio', models.CharField(blank=True, max_length=10)),
                ('nombre_empresa', models.CharField(default='Universidad de Camaguey', max_length=100)),
                ('codigo_reeup', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
            ],
            options={
                'verbose_name': 'Dato de Reporte Diario',
                'verbose_name_plural': 'Datos de Reportes Diarios',
                'unique_together': {('area', 'month', 'year', 'day')},
            },
        ),
    ]
