# Generated by Django 5.1.5 on 2025-04-04 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Cocina C', 'Cocina Comedor'), ('Ciencia A', 'Ciencia Animal'), ('Preparatoria', 'Preparatoria'), ('Sede Martí', 'José Martí'), ('A.Cultural', 'Área Cultural'), ('Laboratorios Tec.', 'Laboratorios Técnicos'), ('Sede Fajardo', 'Manuel Fajardo')], max_length=50)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('plan_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('area', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('react', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mad_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dia_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('react_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='energeticos_app.energyconsumption')),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('energy_consumption', 'day')},
            },
        ),
    ]
