# Generated by Django 5.1.5 on 2025-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumption',
            name='pico_diurno_11am_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyconsumption',
            name='pico_diurno_1pm_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyconsumption',
            name='total_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
