# Generated by Django 5.1.5 on 2025-04-26 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0002_dailyconsumption_pico_diurno_11am_cierre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerdidaConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Cocina C', 'Cocina Comedor'), ('Ciencia A', 'Ciencia Animal'), ('Preparatoria', 'Preparatoria'), ('Sede Martí', 'José Martí'), ('A.Cultural', 'Área Cultural'), ('Laboratorios Tec.', 'Laboratorios Técnicos'), ('Sede Fajardo', 'Manuel Fajardo')], max_length=50)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('consumo_reactivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'unique_together': {('area', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TransformerLossData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Cocina C', 'Cocina Comedor'), ('Ciencia A', 'Ciencia Animal'), ('Preparatoria', 'Preparatoria'), ('Sede Martí', 'José Martí'), ('A.Cultural', 'Área Cultural'), ('Laboratorios Tec.', 'Laboratorios Técnicos'), ('Sede Fajardo', 'Manuel Fajardo')], max_length=50)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('reactive_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transformer Loss Data',
                'verbose_name_plural': 'Transformer Loss Data',
                'unique_together': {('area', 'month', 'year')},
            },
        ),
    ]
