# Generated by Django 5.1.5 on 2025-04-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0003_perdidaconsumption_transformerlossdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerdidaConsumption',
        ),
    ]
