# Generated by Django 5.1.5 on 2025-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0004_delete_perdidaconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformerlossdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transformerlossdata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='transformerlossdata',
            name='monthly_consumption',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transformerlossdata',
            name='reactive_consumption',
            field=models.PositiveIntegerField(),
        ),
    ]
