# Generated by Django 5.1.5 on 2025-04-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0005_remove_transformerlossdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='dia_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='mad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='mad_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='pico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='pico_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='pico_diurno_11am_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='pico_diurno_1pm_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='react',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='react_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='total_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
