# Generated by Django 5.1.5 on 2025-05-03 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0007_alter_dailyconsumption_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='perdidas',
        ),
        migrations.RemoveField(
            model_name='energyconsumption',
            name='plan_mes',
        ),
        migrations.CreateModel(
            name='AreaConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_data', to='energeticos_app.energyconsumption')),
            ],
            options={
                'unique_together': {('energy_consumption',)},
            },
        ),
    ]
