# Generated by Django 5.1.5 on 2025-05-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0008_remove_energyconsumption_perdidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='perdidas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='plan_mes',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AreaConsumptionData',
        ),
    ]
