# Generated by Django 5.1.5 on 2025-05-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0009_energyconsumption_perdidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLocales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_corto', models.CharField(max_length=20, unique=True)),
                ('plan_default', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_pico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor_react', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energeticos_app.arealocales'),
        ),
    ]
