# Generated by Django 5.1.5 on 2025-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0010_arealocales_alter_energyconsumption_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='area',
            field=models.CharField(choices=[('Cocina C', 'Cocina Comedor'), ('Ciencia A', 'Ciencia Animal'), ('Preparatoria', 'Preparatoria'), ('Sede Martí', 'José Martí'), ('A.Cultural', 'Área Cultural'), ('Laboratorios Tec.', 'Laboratorios Técnicos'), ('Sede Fajardo', 'Manuel Fajardo')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AreaLocales',
        ),
    ]
