# Generated by Django 5.1.5 on 2025-05-16 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0011_alter_energyconsumption_area_delete_arealocales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=150)),
                ('sheet_name', models.CharField(max_length=150)),
                ('factor_pico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor_react', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name_area', 'sheet_name')},
            },
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.areadefault'),
        ),
    ]
