# Generated by Django 4.2 on 2025-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0012_areadefault_alter_energyconsumption_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadefault',
            name='default_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
