# Generated by Django 5.1.5 on 2025-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0015_arealocales_delete_areadefault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerlossdata',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
