# Generated by Django 5.1.5 on 2025-06-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0016_alter_transformerlossdata_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerlossdata',
            name='monthly_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transformerlossdata',
            name='reactive_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
