# Generated by Django 5.1.5 on 2025-06-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0018_alter_energyconsumption_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerlossdata',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales'),
        ),
    ]
