# Generated by Django 5.1.5 on 2025-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0019_alter_transformerlossdata_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerlossdata',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
