# Generated by Django 5.1.5 on 2025-06-12 02:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0020_alter_transformerlossdata_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaBitacoraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('react', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_con_pico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_con_react', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_pico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_react', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_plan_pico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_acumulada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_acumulado_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_acumulado_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factor_potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
            ],
            options={
                'verbose_name': 'Dato de Bitácora',
                'verbose_name_plural': 'Datos de Bitácora',
                'unique_together': {('area', 'month', 'year', 'day')},
            },
        ),
    ]
