# Generated by Django 5.1.5 on 2025-06-15 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0021_tablabitacoradata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaBitacoraDataSelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('mad_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dia_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_diurno_11am_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pico_diurno_1pm_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('react_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
            ],
            options={
                'verbose_name': 'Dato de Cierre Mensual',
                'verbose_name_plural': 'Datos de Cierre Mensual',
                'unique_together': {('area', 'month', 'year')},
            },
        ),
    ]
