# Generated by Django 5.1.5 on 2025-06-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0022_tablabitacoradataselete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='perdidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='plan_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
