# Generated by Django 5.1.5 on 2025-06-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0023_alter_energyconsumption_perdidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='plan_mes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
