# Generated by Django 5.1.5 on 2025-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0024_alter_energyconsumption_perdidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformerlossdata',
            name='kva',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='transformerlossdata',
            name='pcu',
            field=models.DecimalField(decimal_places=3, default=0.107, max_digits=10),
        ),
        migrations.AddField(
            model_name='transformerlossdata',
            name='pfe',
            field=models.DecimalField(decimal_places=3, default=0.046, max_digits=10),
        ),
        migrations.AddField(
            model_name='transformerlossdata',
            name='transformer_type',
            field=models.DecimalField(choices=[(5, '5 kVA - Pfe: 0.046, Pcu: 0.107'), (10, '10 kVA - Pfe: 0.065, Pcu: 0.18'), (15, '15 kVA - Pfe: 0.084, Pcu: 0.251'), (25, '25 kVA - Pfe: 0.115, Pcu: 0.389'), (37.5, '37.5 kVA - Pfe: 0.162, Pcu: 0.487'), (50, '50 kVA - Pfe: 0.199, Pcu: 0.626'), (75, '75 kVA - Pfe: 0.269, Pcu: 0.882'), (100, '100 kVA - Pfe: 0.332, Pcu: 1.185'), (167, '167 kVA - Pfe: 0.482, Pcu: 1.893'), (250, '250 kVA - Pfe: 0.66, Pcu: 2.802'), (333, '333 kVA - Pfe: 0.83, Pcu: 3.587')], decimal_places=2, default=5, max_digits=10),
        ),
    ]
