# Generated by Django 5.1.5 on 2025-07-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0025_transformerlossdata_kva_transformerlossdata_pcu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformerlossdata',
            name='transformer_type',
        ),
    ]
