# Generated by Django 5.1.5 on 2025-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0026_remove_transformerlossdata_transformer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
