# Generated by Django 5.1.5 on 2025-07-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0027_energyconsumption_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='updated_at',
        ),
    ]
