# Generated by Django 5.1.5 on 2025-09-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0028_remove_energyconsumption_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.dailyreport')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='areas',
            field=models.ManyToManyField(through='energeticos_app.DailyReportArea', to='energeticos_app.arealocales'),
        ),
    ]
