# Generated by Django 5.1.5 on 2025-09-12 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0029_dailyreport_dailyreportarea_dailyreport_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date'], 'verbose_name': 'Reporte Diario', 'verbose_name_plural': 'Reportes Diarios'},
        ),
        migrations.AlterModelOptions(
            name='dailyreportarea',
            options={'verbose_name': 'Área de Reporte Diario', 'verbose_name_plural': 'Áreas de Reporte Diario'},
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='areas',
        ),
        migrations.AddField(
            model_name='dailyreportarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreportarea',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreportarea',
            unique_together={('daily_report', 'area')},
        ),
    ]
