# Generated by Django 5.1.5 on 2025-09-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0030_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={},
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='date',
            new_name='report_date',
        ),
        migrations.CreateModel(
            name='DailyReportAreaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_total_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diarias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.dailyreport')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='areas',
            field=models.ManyToManyField(through='energeticos_app.DailyReportAreaData', to='energeticos_app.arealocales'),
        ),
        migrations.CreateModel(
            name='PeakReadingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura_11_am', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_1_pm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_5_pm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_9_pm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.dailyreport')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyReportArea',
        ),
    ]
