# Generated by Django 5.1.5 on 2025-09-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0031_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealocales',
            name='es_estatica',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AreaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(default='CAMAGUEY', max_length=50)),
                ('municipio', models.CharField(default='CAMAGUEY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
            ],
            options={
                'verbose_name': 'Configuración de Área',
                'verbose_name_plural': 'Configuraciones de Área',
                'unique_together': {('area',)},
            },
        ),
        migrations.CreateModel(
            name='DiaryStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(default='', max_length=50)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('plan_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('en_uso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.arealocales')),
            ],
            options={
                'verbose_name': 'Área Estática',
                'verbose_name_plural': 'Áreas Estáticas',
                'unique_together': {('area',)},
            },
        ),
    ]
