# Generated by Django 5.1.5 on 2025-09-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0032_arealocales_es_estatica_areaconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['provincia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capital', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='areaconfiguration',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.municipio'),
        ),
        migrations.AlterField(
            model_name='diarystatic',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.municipio'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='energeticos_app.provincia'),
        ),
        migrations.AlterField(
            model_name='areaconfiguration',
            name='provincia',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.provincia'),
        ),
        migrations.AlterField(
            model_name='diarystatic',
            name='provincia',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='energeticos_app.provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('provincia', 'nombre')},
        ),
    ]
