# Generated by Django 5.1.5 on 2025-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0033_municipio_provincia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diarystatic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='diarystatic',
            name='area',
        ),
        migrations.RemoveField(
            model_name='diarystatic',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='diarystatic',
            name='provincia',
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='provincia',
        ),
        migrations.DeleteModel(
            name='AreaConfiguration',
        ),
        migrations.DeleteModel(
            name='DiaryStatic',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
