# Generated by Django 5.1.5 on 2025-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0034_alter_diarystatic_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('plan_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Área Estática',
                'verbose_name_plural': 'Áreas Estáticas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
