# Generated by Django 5.1.5 on 2025-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0035_areaestatica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaestatica',
            options={'ordering': ['nombre'], 'verbose_name': 'Área Estática', 'verbose_name_plural': 'Áreas Estáticas'},
        ),
        migrations.RemoveField(
            model_name='areaestatica',
            name='orden',
        ),
        migrations.AddField(
            model_name='areaestatica',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areaestatica',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Pinar del Río', 'Pinar del Río'), ('Artemisa', 'Artemisa'), ('La Habana', 'La Habana'), ('Mayabeque', 'Mayabeque'), ('Matanzas', 'Matanzas'), ('Cienfuegos', 'Cienfuegos'), ('Villa Clara', 'Villa Clara'), ('Sancti Spíritus', 'Sancti Spíritus'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Camagüey', 'Camagüey'), ('Las Tunas', 'Las Tunas'), ('Holguín', 'Holguín'), ('Granma', 'Granma'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Guantánamo', 'Guantánamo')], max_length=50, null=True),
        ),
    ]
