# Generated by Django 5.1.5 on 2025-09-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0036_alter_areaestatica_options_remove_areaestatica_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaestatica',
            name='area_local',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_estatica', to='energeticos_app.arealocales'),
        ),
    ]
