# Generated by Django 5.1.5 on 2025-09-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energeticos_app', '0037_areaestatica_area_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaestatica',
            name='area_local',
        ),
    ]
