# Generated by Django 5.1.5 on 2025-03-14 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMRContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('numeroCuenta', models.IntegerField(blank=True, null=True)),
                ('numeroCliente', models.IntegerField(blank=True, null=True)),
                ('direccionDispositivo', models.CharField(blank=True, max_length=600, null=True)),
                ('numeroContador', models.CharField(blank=True, max_length=150, null=True)),
                ('nombreContador', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'unique_together': {('numeroContador',)},
            },
        ),
        migrations.CreateModel(
            name='AMRDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmpLectura', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('totalImpEnerg', models.FloatField(blank=True, null=True)),
                ('t1ImpEnerg', models.FloatField(blank=True, null=True)),
                ('t2ImpEnerg', models.FloatField(blank=True, null=True)),
                ('t3ImpEnerg', models.FloatField(blank=True, null=True)),
                ('totalExpEnerg', models.FloatField(blank=True, null=True)),
                ('t1ExpEnerg', models.FloatField(blank=True, null=True)),
                ('t2ExpEnerg', models.FloatField(blank=True, null=True)),
                ('t3ExpEnerg', models.FloatField(blank=True, null=True)),
                ('totalImpReacEnerg', models.FloatField(blank=True, null=True)),
                ('t1ImpMaxDeman', models.FloatField(blank=True, null=True)),
                ('t2ImpMaxDeman', models.FloatField(blank=True, null=True)),
                ('t3ImpMaxDeman', models.FloatField(blank=True, null=True)),
                ('t1ExpMaxDeman', models.FloatField(blank=True, null=True)),
                ('t2ExpMaxDeman', models.FloatField(blank=True, null=True)),
                ('t3ExpMaxDeman', models.FloatField(blank=True, null=True)),
                ('imporActPoder', models.FloatField(blank=True, null=True)),
                ('exporActPoder', models.FloatField(blank=True, null=True)),
                ('factPoder', models.FloatField(blank=True, null=True)),
                ('faceAVolt', models.FloatField(blank=True, null=True)),
                ('faceBVolt', models.FloatField(blank=True, null=True)),
                ('faceCVolt', models.FloatField(blank=True, null=True)),
                ('faceACurr', models.FloatField(blank=True, null=True)),
                ('faceBCurr', models.FloatField(blank=True, null=True)),
                ('faceCCurr', models.FloatField(blank=True, null=True)),
                ('amrContador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amr_app.amrcontador')),
            ],
            options={
                'ordering': ['-tmpLectura'],
            },
        ),
    ]
