# Generated by Django 5.1.5 on 2025-03-14 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amrcontador',
            name='direccionDispositivo',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Dirección dispositivo'),
        ),
        migrations.AlterField(
            model_name='amrcontador',
            name='nombreContador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre contador'),
        ),
        migrations.AlterField(
            model_name='amrcontador',
            name='numeroCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de cliente'),
        ),
        migrations.AlterField(
            model_name='amrcontador',
            name='numeroContador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número contador'),
        ),
        migrations.AlterField(
            model_name='amrcontador',
            name='numeroCuenta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='amrcontador',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='amrContador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amr_app.amrcontador', verbose_name='AMR'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='exporActPoder',
            field=models.FloatField(blank=True, null=True, verbose_name='Exporte activo de poder (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceACurr',
            field=models.FloatField(blank=True, null=True, verbose_name='Face A de corriente (A)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceAVolt',
            field=models.FloatField(blank=True, null=True, verbose_name='Face A de voltage (V)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceBCurr',
            field=models.FloatField(blank=True, null=True, verbose_name='Face B de corriente (A)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceBVolt',
            field=models.FloatField(blank=True, null=True, verbose_name='Face B de voltage (V)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceCCurr',
            field=models.FloatField(blank=True, null=True, verbose_name='Face C de corriente (A)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='faceCVolt',
            field=models.FloatField(blank=True, null=True, verbose_name='Face C de voltage (V)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='factPoder',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de poder'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='imporActPoder',
            field=models.FloatField(blank=True, null=True, verbose_name='Importe activo de poder (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t1ExpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T1 exporte de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t1ExpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T1 exporte activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t1ImpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T1 importe de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t1ImpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T1 importe activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t2ExpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T2 exporte de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t2ExpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T2 exporte activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t2ImpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T2 importe de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t2ImpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T2 importe activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t3ExpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T3 exporte de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t3ExpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T3 exporte activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t3ImpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='T3 importe de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='t3ImpMaxDeman',
            field=models.FloatField(blank=True, null=True, verbose_name='T3 importe activo maximo demandado (kW)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='tmpLectura',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Tiempo de Lectura'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='totalExpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total exporte de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='totalImpEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total importe de energía activa (kWh)'),
        ),
        migrations.AlterField(
            model_name='amrdatos',
            name='totalImpReacEnerg',
            field=models.FloatField(blank=True, null=True, verbose_name='Total importe de energía reactiva (kvarh)'),
        ),
    ]
