# Generated by Django 5.1.5 on 2025-04-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amr_app', '0002_alter_amrcontador_direcciondispositivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amrdatos',
            options={'ordering': ['tmpLectura']},
        ),
    ]
