# Generated by Django 5.1.5 on 2025-03-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspeccion_time', models.DateField(auto_now_add=True)),
                ('tipo_inspeccion', models.CharField(max_length=200)),
                ('nombre_inpectores', models.CharField(max_length=200)),
                ('deficiencias_violaciones', models.TextField()),
                ('plan_acciones', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cliente')),
            ],
        ),
    ]
